---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.add_certificates"
      tags:
      - "labocbz.add_certificates"
      loop: "{{ inv_add_certificates }}"
      loop_control:
        loop_var: bundle
      when: inv_add_certificates is defined
      vars:
        add_certificates__bundle_name: "{{ bundle.name }}"
        add_certificates__bundle_type: "{{ bundle.type }}"
        add_certificates__bundle_src: "{{ bundle.src }}"
        add_certificates__bundle_dest: "{{ bundle.dest }}"
        add_certificates__bundle_src_user: "{{ bundle.src_user }}"
        add_certificates__bundle_src_password: "{{ bundle.src_password }}"
        add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
        add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
        add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
      ansible.builtin.include_role:
        name: "labocbz.add_certificates"
